# Generated by Django 5.2 on 2025-05-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        choices=[
                            ("RELIANCE.NS", "Reliance"),
                            ("TCS.NS", "TCS"),
                            ("INFY.NS", "Infosys"),
                            ("HDFCBANK.NS", "HDFC Bank"),
                            ("ICICIBANK.NS", "ICICI Bank"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
